<?xml version="1.0" encoding="utf-8"?><Database Name="ZdravstveniCentar" Class="DataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DARKO-PC\SQLEXPRESS;Initial Catalog=ZdravstveniCentar;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=True" SettingsObjectName="BazaN.Properties.Settings" SettingsPropertyName="ZdravstveniCentarConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Pacijent" Member="Pacijents">
    <Type Name="Pacijent">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Ime" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Prezime" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="JMBG" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Alergeni" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Id_Lekara" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Pacijent_Pregled" Member="Pregleds" ThisKey="Id" OtherKey="Id_Pacijenta" Type="Pregled" />
      <Association Name="Pacijent_Terapija" Member="Terapijas" ThisKey="Id" OtherKey="Id_Pacijenta" Type="Terapija" />
      <Association Name="Pacijent_Uput" Member="Uputs" ThisKey="Id" OtherKey="Id_Pacijenta" Type="Uput" />
    </Type>
  </Table>
  <Table Name="dbo.Pregled" Member="Pregleds">
    <Type Name="Pregled">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Id_Lekara" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Id_Pacijenta" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Opis" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Id_ZS" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Datum" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Pacijent_Pregled" Member="Pacijent" ThisKey="Id_Pacijenta" OtherKey="Id" Type="Pacijent" IsForeignKey="true" />
      <Association Name="Zaposleni_Pregled" Member="Zaposleni" ThisKey="Id_Lekara" OtherKey="Id" Type="Zaposleni" IsForeignKey="true" />
      <Association Name="ZdravstvenaUstanova_Pregled" Member="ZdravstvenaUstanova" ThisKey="Id_ZS" OtherKey="Id" Type="ZdravstvenaUstanova" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Terapija" Member="Terapijas">
    <Type Name="Terapija">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Id_Lekara" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Id_Pacijenta" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Opis" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Datum" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Dijagnoza" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Association Name="Pacijent_Terapija" Member="Pacijent" ThisKey="Id_Pacijenta" OtherKey="Id" Type="Pacijent" IsForeignKey="true" />
      <Association Name="Zaposleni_Terapija" Member="Zaposleni" ThisKey="Id_Lekara" OtherKey="Id" Type="Zaposleni" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TipZaposlenog" Member="TipZaposlenogs">
    <Type Name="TipZaposlenog">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TipZ" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Opis" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="TipZaposlenog_Zaposleni" Member="Zaposlenis" ThisKey="Id" OtherKey="Tip" Type="Zaposleni" />
    </Type>
  </Table>
  <Table Name="dbo.Uput" Member="Uputs">
    <Type Name="Uput">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Id_Lekara" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Id_Pacijenta" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Opis" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Id_ZS" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Datum" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Pacijent_Uput" Member="Pacijent" ThisKey="Id_Pacijenta" OtherKey="Id" Type="Pacijent" IsForeignKey="true" />
      <Association Name="Zaposleni_Uput" Member="Zaposleni" ThisKey="Id_Lekara" OtherKey="Id" Type="Zaposleni" IsForeignKey="true" />
      <Association Name="ZdravstvenaUstanova_Uput" Member="ZdravstvenaUstanova" ThisKey="Id_ZS" OtherKey="Id" Type="ZdravstvenaUstanova" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Zaposleni" Member="Zaposlenis">
    <Type Name="Zaposleni">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Ime" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Prezime" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="JMBG" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Tip" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Radi" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Smena" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Id_ZS" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Zaposleni_Pregled" Member="Pregleds" ThisKey="Id" OtherKey="Id_Lekara" Type="Pregled" />
      <Association Name="Zaposleni_Terapija" Member="Terapijas" ThisKey="Id" OtherKey="Id_Lekara" Type="Terapija" />
      <Association Name="Zaposleni_Uput" Member="Uputs" ThisKey="Id" OtherKey="Id_Lekara" Type="Uput" />
      <Association Name="TipZaposlenog_Zaposleni" Member="TipZaposlenog" ThisKey="Tip" OtherKey="Id" Type="TipZaposlenog" IsForeignKey="true" />
      <Association Name="ZdravstvenaUstanova_Zaposleni" Member="ZdravstvenaUstanova" ThisKey="Id_ZS" OtherKey="Id" Type="ZdravstvenaUstanova" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ZdravstvenaUstanova" Member="ZdravstvenaUstanovas">
    <Type Name="ZdravstvenaUstanova">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Naziv" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Adresa" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Grad" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="ZdravstvenaUstanova_Pregled" Member="Pregleds" ThisKey="Id" OtherKey="Id_ZS" Type="Pregled" />
      <Association Name="ZdravstvenaUstanova_Uput" Member="Uputs" ThisKey="Id" OtherKey="Id_ZS" Type="Uput" />
      <Association Name="ZdravstvenaUstanova_Zaposleni" Member="Zaposlenis" ThisKey="Id" OtherKey="Id_ZS" Type="Zaposleni" />
    </Type>
  </Table>
</Database>